# Generated by Django 6.0.7 on 2026-07-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('skills', models.CharField(help_text='Example: Python, Django, React', max_length=300)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
